services:
  - type: web
    name: mychat
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRY
        value: 7d
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mychat-db
          property: connectionString

databases:
  - name: mychat-db
    databaseName: mychat
    user: mychat_user 